//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_budget_expense.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetRecord
    {
        public int BudgetID { get; set; }
        public System.DateTime DateOfTrans { get; set; }
        public int UserID { get; set; }
        public string TypeOfTrans { get; set; }
        public string TransDescription { get; set; }
        public double Amount { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
